<?php

namespace OrderBundle\Repository;

/**
 * DevisItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevisItemRepository extends \Doctrine\ORM\EntityRepository
{
}
